package cn.bjd.platform.elastic.provider.mapper;

import cn.bjd.platform.elastic.api.entity.CrdBreakfaith;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CrdBreakfaithMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insert(CrdBreakfaith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insertSelective(CrdBreakfaith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    CrdBreakfaith selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(CrdBreakfaith record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_breakfaith
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKey(CrdBreakfaith record);

    List<CrdBreakfaith> findByEtpId(@Param("company") String company);

    List<CrdBreakfaith> findByPersonNameIn(@Param("personNameList") List<String> personNameList);

    /**
     * 根据企业名查询失信数量
     *
     * @param company
     * @return int
     */
    int findCountByEtpName(@Param("company") String company);
}