package cn.bjd.platform.elastic.provider.mapper;

import cn.bjd.platform.elastic.api.entity.CrdCourtpub;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface CrdCourtpubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insert(CrdCourtpub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insertSelective(CrdCourtpub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    CrdCourtpub selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(CrdCourtpub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_courtpub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKey(CrdCourtpub record);

     List<CrdCourtpub> findByEtpId(@Param("etpId") String etpId);

     List<CrdCourtpub> findByEtpIdIn(@Param("etpIdList") List<String> etpIdList);
}