package cn.bjd.platform.elastic.provider.mapper;

import cn.bjd.platform.elastic.api.entity.CrdCourt;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CrdCourtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insert(CrdCourt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insertSelective(CrdCourt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    CrdCourt selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(CrdCourt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKey(CrdCourt record);

    List<CrdCourt> findByEtpId(@Param("etpId") String etpId, @Param("type") String type);

    List<CrdCourt> findByEtpIdIn(@Param("etpIdList") List<String> etpIdList, @Param("type") String type);

    /**
     * 根据企业名获取裁判文书中为被告的数量
     *
     * @param name
     * @param type
     * @return int
     */
    int findCountByEtpName(@Param("name") String name, @Param("type") String type);
}