package cn.bjd.platform.elastic.provider.mapper;

import cn.bjd.platform.elastic.api.entity.CrdExecuted;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CrdExecutedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insert(CrdExecuted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int insertSelective(CrdExecuted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    CrdExecuted selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKeySelective(CrdExecuted record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_executed
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    int updateByPrimaryKey(CrdExecuted record);

    List<CrdExecuted> findByEtpId(@Param("executed") String executed);

    List<CrdExecuted> findByExecutedIn(@Param("executedList") List<String> executedList);

    /**
     * 根据企业名获取被执行人数量
     *
     * @param executed
     * @return int
     */
    int findCountByExecuted(@Param("executed") String executed);
}