package cn.bjd.platform.elastic.provider.mapper;


import cn.bjd.platform.elastic.api.entity.Industry;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface IndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    int insert(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    int insertSelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    Industry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    int updateByPrimaryKeySelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.industry
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    int updateByPrimaryKey(Industry record);

    List<Industry> findAll();
}