package cn.bjd.platform.elastic.api.entity;

import java.util.Date;

public class CrdCourtpub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.id
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.case_cause
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String caseCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.province
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.city
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.area
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.client
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String client;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.clients
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.court_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String courtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.data_from
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.detail_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String detailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.is_court_pub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String isCourtPub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.judges
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String judges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.path
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.pdf_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String pdfLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.person_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.pub_content
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String pubContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.pub_person
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String pubPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.pub_type
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String pubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.source
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.subject
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.summary
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.pub_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date pubDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.modify_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.collect_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date collectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.collect_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.flag
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.create_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_courtpub.update_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    private Date updateTime;

    private String etpId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.id
     *
     * @return the value of public.crd_courtpub.id
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.id
     *
     * @param id the value for public.crd_courtpub.id
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.case_cause
     *
     * @return the value of public.crd_courtpub.case_cause
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getCaseCause() {
        return caseCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.case_cause
     *
     * @param caseCause the value for public.crd_courtpub.case_cause
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCaseCause(String caseCause) {
        this.caseCause = caseCause == null ? null : caseCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.province
     *
     * @return the value of public.crd_courtpub.province
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.province
     *
     * @param province the value for public.crd_courtpub.province
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.city
     *
     * @return the value of public.crd_courtpub.city
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.city
     *
     * @param city the value for public.crd_courtpub.city
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.area
     *
     * @return the value of public.crd_courtpub.area
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.area
     *
     * @param area the value for public.crd_courtpub.area
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.client
     *
     * @return the value of public.crd_courtpub.client
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.client
     *
     * @param client the value for public.crd_courtpub.client
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setClient(String client) {
        this.client = client == null ? null : client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.clients
     *
     * @return the value of public.crd_courtpub.clients
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.clients
     *
     * @param clients the value for public.crd_courtpub.clients
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.court_name
     *
     * @return the value of public.crd_courtpub.court_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getCourtName() {
        return courtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.court_name
     *
     * @param courtName the value for public.crd_courtpub.court_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCourtName(String courtName) {
        this.courtName = courtName == null ? null : courtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.data_from
     *
     * @return the value of public.crd_courtpub.data_from
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.data_from
     *
     * @param dataFrom the value for public.crd_courtpub.data_from
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.detail_link
     *
     * @return the value of public.crd_courtpub.detail_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getDetailLink() {
        return detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.detail_link
     *
     * @param detailLink the value for public.crd_courtpub.detail_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink == null ? null : detailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.is_court_pub
     *
     * @return the value of public.crd_courtpub.is_court_pub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getIsCourtPub() {
        return isCourtPub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.is_court_pub
     *
     * @param isCourtPub the value for public.crd_courtpub.is_court_pub
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setIsCourtPub(String isCourtPub) {
        this.isCourtPub = isCourtPub == null ? null : isCourtPub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.judges
     *
     * @return the value of public.crd_courtpub.judges
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getJudges() {
        return judges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.judges
     *
     * @param judges the value for public.crd_courtpub.judges
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setJudges(String judges) {
        this.judges = judges == null ? null : judges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.path
     *
     * @return the value of public.crd_courtpub.path
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.path
     *
     * @param path the value for public.crd_courtpub.path
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.pdf_link
     *
     * @return the value of public.crd_courtpub.pdf_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPdfLink() {
        return pdfLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.pdf_link
     *
     * @param pdfLink the value for public.crd_courtpub.pdf_link
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPdfLink(String pdfLink) {
        this.pdfLink = pdfLink == null ? null : pdfLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.person_name
     *
     * @return the value of public.crd_courtpub.person_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.person_name
     *
     * @param personName the value for public.crd_courtpub.person_name
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.pub_content
     *
     * @return the value of public.crd_courtpub.pub_content
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPubContent() {
        return pubContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.pub_content
     *
     * @param pubContent the value for public.crd_courtpub.pub_content
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPubContent(String pubContent) {
        this.pubContent = pubContent == null ? null : pubContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.pub_person
     *
     * @return the value of public.crd_courtpub.pub_person
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPubPerson() {
        return pubPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.pub_person
     *
     * @param pubPerson the value for public.crd_courtpub.pub_person
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPubPerson(String pubPerson) {
        this.pubPerson = pubPerson == null ? null : pubPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.pub_type
     *
     * @return the value of public.crd_courtpub.pub_type
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getPubType() {
        return pubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.pub_type
     *
     * @param pubType the value for public.crd_courtpub.pub_type
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPubType(String pubType) {
        this.pubType = pubType == null ? null : pubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.source
     *
     * @return the value of public.crd_courtpub.source
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.source
     *
     * @param source the value for public.crd_courtpub.source
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.subject
     *
     * @return the value of public.crd_courtpub.subject
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.subject
     *
     * @param subject the value for public.crd_courtpub.subject
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.summary
     *
     * @return the value of public.crd_courtpub.summary
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.summary
     *
     * @param summary the value for public.crd_courtpub.summary
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.pub_date
     *
     * @return the value of public.crd_courtpub.pub_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.pub_date
     *
     * @param pubDate the value for public.crd_courtpub.pub_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.modify_date
     *
     * @return the value of public.crd_courtpub.modify_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.modify_date
     *
     * @param modifyDate the value for public.crd_courtpub.modify_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.collect_date
     *
     * @return the value of public.crd_courtpub.collect_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getCollectDate() {
        return collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.collect_date
     *
     * @param collectDate the value for public.crd_courtpub.collect_date
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCollectDate(Date collectDate) {
        this.collectDate = collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.collect_time
     *
     * @return the value of public.crd_courtpub.collect_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.collect_time
     *
     * @param collectTime the value for public.crd_courtpub.collect_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.flag
     *
     * @return the value of public.crd_courtpub.flag
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.flag
     *
     * @param flag the value for public.crd_courtpub.flag
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.create_time
     *
     * @return the value of public.crd_courtpub.create_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.create_time
     *
     * @param createTime the value for public.crd_courtpub.create_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_courtpub.update_time
     *
     * @return the value of public.crd_courtpub.update_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_courtpub.update_time
     *
     * @param updateTime the value for public.crd_courtpub.update_time
     *
     * @mbggenerated Thu Jan 11 15:56:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * Gets etpId
     *
     * @return value of etpId
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * @param etpId
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId;
    }
}