package cn.bjd.platform.elastic.api.entity;

import java.math.BigDecimal;

public class Industry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.pid
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_level
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private Integer iLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_path
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.type_xxl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String typeXxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.type_xl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String typeXl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.type_ml
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String typeMl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.type_sl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String typeSl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_name
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.priority1
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String priority1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.priority2
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String priority2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.priority1_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal priority1Value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.priority2_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal priority2Value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.credit_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal creditValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_feature
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.danger_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String dangerDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.danger_publish
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String dangerPublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.danger_against
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String dangerAgainst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_baseline
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iBaseline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.credit_guide
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String creditGuide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.s_cw_excellent_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal sCwExcellent15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.s_cw_avg_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal sCwAvg15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_up_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iUpCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_down_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDownCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_up_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iUpIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_down_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDownIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_up
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_down
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_up_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iUpColors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_down_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDownColors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.credit_data
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal creditData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.credit_excellent
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal creditExcellent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.credit_avg
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal creditAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_color
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_down_mask
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iDownMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.total_score
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private Integer totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.i_btype
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String iBtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.hy_img
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String hyImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.added_tax
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal addedTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_mc
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_sxyz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylSxyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_zdqy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylZdqy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_hy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylHy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_zrbz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylZrbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_jbzrtj
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylJbzrtj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_tz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylTz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_fxsb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylFxsb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.cyl_fxgkcs
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String cylFxgkcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.tz_code
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String tzCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.season_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private Integer seasonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.rgcb_zb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private BigDecimal rgcbZb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.industry.news_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    private String newsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.id
     *
     * @return the value of public.industry.id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.id
     *
     * @param id the value for public.industry.id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.pid
     *
     * @return the value of public.industry.pid
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.pid
     *
     * @param pid the value for public.industry.pid
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_level
     *
     * @return the value of public.industry.i_level
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public Integer getiLevel() {
        return iLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_level
     *
     * @param iLevel the value for public.industry.i_level
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiLevel(Integer iLevel) {
        this.iLevel = iLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_path
     *
     * @return the value of public.industry.i_path
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiPath() {
        return iPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_path
     *
     * @param iPath the value for public.industry.i_path
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiPath(String iPath) {
        this.iPath = iPath == null ? null : iPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.type_xxl
     *
     * @return the value of public.industry.type_xxl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getTypeXxl() {
        return typeXxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.type_xxl
     *
     * @param typeXxl the value for public.industry.type_xxl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTypeXxl(String typeXxl) {
        this.typeXxl = typeXxl == null ? null : typeXxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.type_xl
     *
     * @return the value of public.industry.type_xl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getTypeXl() {
        return typeXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.type_xl
     *
     * @param typeXl the value for public.industry.type_xl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTypeXl(String typeXl) {
        this.typeXl = typeXl == null ? null : typeXl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.type_ml
     *
     * @return the value of public.industry.type_ml
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getTypeMl() {
        return typeMl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.type_ml
     *
     * @param typeMl the value for public.industry.type_ml
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTypeMl(String typeMl) {
        this.typeMl = typeMl == null ? null : typeMl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.type_sl
     *
     * @return the value of public.industry.type_sl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getTypeSl() {
        return typeSl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.type_sl
     *
     * @param typeSl the value for public.industry.type_sl
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTypeSl(String typeSl) {
        this.typeSl = typeSl == null ? null : typeSl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_name
     *
     * @return the value of public.industry.i_name
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiName() {
        return iName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_name
     *
     * @param iName the value for public.industry.i_name
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiName(String iName) {
        this.iName = iName == null ? null : iName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_des
     *
     * @return the value of public.industry.i_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDes() {
        return iDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_des
     *
     * @param iDes the value for public.industry.i_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDes(String iDes) {
        this.iDes = iDes == null ? null : iDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.priority1
     *
     * @return the value of public.industry.priority1
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getPriority1() {
        return priority1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.priority1
     *
     * @param priority1 the value for public.industry.priority1
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setPriority1(String priority1) {
        this.priority1 = priority1 == null ? null : priority1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.priority2
     *
     * @return the value of public.industry.priority2
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getPriority2() {
        return priority2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.priority2
     *
     * @param priority2 the value for public.industry.priority2
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setPriority2(String priority2) {
        this.priority2 = priority2 == null ? null : priority2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.priority1_value
     *
     * @return the value of public.industry.priority1_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getPriority1Value() {
        return priority1Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.priority1_value
     *
     * @param priority1Value the value for public.industry.priority1_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setPriority1Value(BigDecimal priority1Value) {
        this.priority1Value = priority1Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.priority2_value
     *
     * @return the value of public.industry.priority2_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getPriority2Value() {
        return priority2Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.priority2_value
     *
     * @param priority2Value the value for public.industry.priority2_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setPriority2Value(BigDecimal priority2Value) {
        this.priority2Value = priority2Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.credit_value
     *
     * @return the value of public.industry.credit_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getCreditValue() {
        return creditValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.credit_value
     *
     * @param creditValue the value for public.industry.credit_value
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCreditValue(BigDecimal creditValue) {
        this.creditValue = creditValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_feature
     *
     * @return the value of public.industry.i_feature
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiFeature() {
        return iFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_feature
     *
     * @param iFeature the value for public.industry.i_feature
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiFeature(String iFeature) {
        this.iFeature = iFeature == null ? null : iFeature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.danger_des
     *
     * @return the value of public.industry.danger_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getDangerDes() {
        return dangerDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.danger_des
     *
     * @param dangerDes the value for public.industry.danger_des
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setDangerDes(String dangerDes) {
        this.dangerDes = dangerDes == null ? null : dangerDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.danger_publish
     *
     * @return the value of public.industry.danger_publish
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getDangerPublish() {
        return dangerPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.danger_publish
     *
     * @param dangerPublish the value for public.industry.danger_publish
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setDangerPublish(String dangerPublish) {
        this.dangerPublish = dangerPublish == null ? null : dangerPublish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.danger_against
     *
     * @return the value of public.industry.danger_against
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getDangerAgainst() {
        return dangerAgainst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.danger_against
     *
     * @param dangerAgainst the value for public.industry.danger_against
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setDangerAgainst(String dangerAgainst) {
        this.dangerAgainst = dangerAgainst == null ? null : dangerAgainst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_baseline
     *
     * @return the value of public.industry.i_baseline
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiBaseline() {
        return iBaseline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_baseline
     *
     * @param iBaseline the value for public.industry.i_baseline
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiBaseline(String iBaseline) {
        this.iBaseline = iBaseline == null ? null : iBaseline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.credit_guide
     *
     * @return the value of public.industry.credit_guide
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCreditGuide() {
        return creditGuide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.credit_guide
     *
     * @param creditGuide the value for public.industry.credit_guide
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCreditGuide(String creditGuide) {
        this.creditGuide = creditGuide == null ? null : creditGuide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.s_cw_excellent_15
     *
     * @return the value of public.industry.s_cw_excellent_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getsCwExcellent15() {
        return sCwExcellent15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.s_cw_excellent_15
     *
     * @param sCwExcellent15 the value for public.industry.s_cw_excellent_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setsCwExcellent15(BigDecimal sCwExcellent15) {
        this.sCwExcellent15 = sCwExcellent15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.s_cw_avg_15
     *
     * @return the value of public.industry.s_cw_avg_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getsCwAvg15() {
        return sCwAvg15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.s_cw_avg_15
     *
     * @param sCwAvg15 the value for public.industry.s_cw_avg_15
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setsCwAvg15(BigDecimal sCwAvg15) {
        this.sCwAvg15 = sCwAvg15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_up_codes
     *
     * @return the value of public.industry.i_up_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiUpCodes() {
        return iUpCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_up_codes
     *
     * @param iUpCodes the value for public.industry.i_up_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiUpCodes(String iUpCodes) {
        this.iUpCodes = iUpCodes == null ? null : iUpCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_down_codes
     *
     * @return the value of public.industry.i_down_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDownCodes() {
        return iDownCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_down_codes
     *
     * @param iDownCodes the value for public.industry.i_down_codes
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDownCodes(String iDownCodes) {
        this.iDownCodes = iDownCodes == null ? null : iDownCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_up_ids
     *
     * @return the value of public.industry.i_up_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiUpIds() {
        return iUpIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_up_ids
     *
     * @param iUpIds the value for public.industry.i_up_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiUpIds(String iUpIds) {
        this.iUpIds = iUpIds == null ? null : iUpIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_down_ids
     *
     * @return the value of public.industry.i_down_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDownIds() {
        return iDownIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_down_ids
     *
     * @param iDownIds the value for public.industry.i_down_ids
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDownIds(String iDownIds) {
        this.iDownIds = iDownIds == null ? null : iDownIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_up
     *
     * @return the value of public.industry.i_up
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiUp() {
        return iUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_up
     *
     * @param iUp the value for public.industry.i_up
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiUp(String iUp) {
        this.iUp = iUp == null ? null : iUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_down
     *
     * @return the value of public.industry.i_down
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDown() {
        return iDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_down
     *
     * @param iDown the value for public.industry.i_down
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDown(String iDown) {
        this.iDown = iDown == null ? null : iDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_up_colors
     *
     * @return the value of public.industry.i_up_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiUpColors() {
        return iUpColors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_up_colors
     *
     * @param iUpColors the value for public.industry.i_up_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiUpColors(String iUpColors) {
        this.iUpColors = iUpColors == null ? null : iUpColors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_down_colors
     *
     * @return the value of public.industry.i_down_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDownColors() {
        return iDownColors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_down_colors
     *
     * @param iDownColors the value for public.industry.i_down_colors
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDownColors(String iDownColors) {
        this.iDownColors = iDownColors == null ? null : iDownColors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.credit_data
     *
     * @return the value of public.industry.credit_data
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getCreditData() {
        return creditData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.credit_data
     *
     * @param creditData the value for public.industry.credit_data
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCreditData(BigDecimal creditData) {
        this.creditData = creditData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.credit_excellent
     *
     * @return the value of public.industry.credit_excellent
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getCreditExcellent() {
        return creditExcellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.credit_excellent
     *
     * @param creditExcellent the value for public.industry.credit_excellent
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCreditExcellent(BigDecimal creditExcellent) {
        this.creditExcellent = creditExcellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.credit_avg
     *
     * @return the value of public.industry.credit_avg
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getCreditAvg() {
        return creditAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.credit_avg
     *
     * @param creditAvg the value for public.industry.credit_avg
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCreditAvg(BigDecimal creditAvg) {
        this.creditAvg = creditAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_color
     *
     * @return the value of public.industry.i_color
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiColor() {
        return iColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_color
     *
     * @param iColor the value for public.industry.i_color
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiColor(String iColor) {
        this.iColor = iColor == null ? null : iColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_down_mask
     *
     * @return the value of public.industry.i_down_mask
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiDownMask() {
        return iDownMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_down_mask
     *
     * @param iDownMask the value for public.industry.i_down_mask
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiDownMask(String iDownMask) {
        this.iDownMask = iDownMask == null ? null : iDownMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.total_score
     *
     * @return the value of public.industry.total_score
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.total_score
     *
     * @param totalScore the value for public.industry.total_score
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.i_btype
     *
     * @return the value of public.industry.i_btype
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getiBtype() {
        return iBtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.i_btype
     *
     * @param iBtype the value for public.industry.i_btype
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setiBtype(String iBtype) {
        this.iBtype = iBtype == null ? null : iBtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.hy_img
     *
     * @return the value of public.industry.hy_img
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getHyImg() {
        return hyImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.hy_img
     *
     * @param hyImg the value for public.industry.hy_img
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setHyImg(String hyImg) {
        this.hyImg = hyImg == null ? null : hyImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.added_tax
     *
     * @return the value of public.industry.added_tax
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getAddedTax() {
        return addedTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.added_tax
     *
     * @param addedTax the value for public.industry.added_tax
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setAddedTax(BigDecimal addedTax) {
        this.addedTax = addedTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_mc
     *
     * @return the value of public.industry.cyl_mc
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylMc() {
        return cylMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_mc
     *
     * @param cylMc the value for public.industry.cyl_mc
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylMc(String cylMc) {
        this.cylMc = cylMc == null ? null : cylMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_sxyz
     *
     * @return the value of public.industry.cyl_sxyz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylSxyz() {
        return cylSxyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_sxyz
     *
     * @param cylSxyz the value for public.industry.cyl_sxyz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylSxyz(String cylSxyz) {
        this.cylSxyz = cylSxyz == null ? null : cylSxyz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_zdqy
     *
     * @return the value of public.industry.cyl_zdqy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylZdqy() {
        return cylZdqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_zdqy
     *
     * @param cylZdqy the value for public.industry.cyl_zdqy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylZdqy(String cylZdqy) {
        this.cylZdqy = cylZdqy == null ? null : cylZdqy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_hy
     *
     * @return the value of public.industry.cyl_hy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylHy() {
        return cylHy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_hy
     *
     * @param cylHy the value for public.industry.cyl_hy
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylHy(String cylHy) {
        this.cylHy = cylHy == null ? null : cylHy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_zrbz
     *
     * @return the value of public.industry.cyl_zrbz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylZrbz() {
        return cylZrbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_zrbz
     *
     * @param cylZrbz the value for public.industry.cyl_zrbz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylZrbz(String cylZrbz) {
        this.cylZrbz = cylZrbz == null ? null : cylZrbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_jbzrtj
     *
     * @return the value of public.industry.cyl_jbzrtj
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylJbzrtj() {
        return cylJbzrtj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_jbzrtj
     *
     * @param cylJbzrtj the value for public.industry.cyl_jbzrtj
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylJbzrtj(String cylJbzrtj) {
        this.cylJbzrtj = cylJbzrtj == null ? null : cylJbzrtj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_tz
     *
     * @return the value of public.industry.cyl_tz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylTz() {
        return cylTz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_tz
     *
     * @param cylTz the value for public.industry.cyl_tz
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylTz(String cylTz) {
        this.cylTz = cylTz == null ? null : cylTz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_fxsb
     *
     * @return the value of public.industry.cyl_fxsb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylFxsb() {
        return cylFxsb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_fxsb
     *
     * @param cylFxsb the value for public.industry.cyl_fxsb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylFxsb(String cylFxsb) {
        this.cylFxsb = cylFxsb == null ? null : cylFxsb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.cyl_fxgkcs
     *
     * @return the value of public.industry.cyl_fxgkcs
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getCylFxgkcs() {
        return cylFxgkcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.cyl_fxgkcs
     *
     * @param cylFxgkcs the value for public.industry.cyl_fxgkcs
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setCylFxgkcs(String cylFxgkcs) {
        this.cylFxgkcs = cylFxgkcs == null ? null : cylFxgkcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.tz_code
     *
     * @return the value of public.industry.tz_code
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getTzCode() {
        return tzCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.tz_code
     *
     * @param tzCode the value for public.industry.tz_code
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setTzCode(String tzCode) {
        this.tzCode = tzCode == null ? null : tzCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.season_id
     *
     * @return the value of public.industry.season_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public Integer getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.season_id
     *
     * @param seasonId the value for public.industry.season_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.rgcb_zb
     *
     * @return the value of public.industry.rgcb_zb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public BigDecimal getRgcbZb() {
        return rgcbZb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.rgcb_zb
     *
     * @param rgcbZb the value for public.industry.rgcb_zb
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setRgcbZb(BigDecimal rgcbZb) {
        this.rgcbZb = rgcbZb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.industry.news_id
     *
     * @return the value of public.industry.news_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public String getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.industry.news_id
     *
     * @param newsId the value for public.industry.news_id
     *
     * @mbggenerated Sat Jan 13 00:55:19 CST 2018
     */
    public void setNewsId(String newsId) {
        this.newsId = newsId == null ? null : newsId.trim();
    }
}